name: Android UI Test (Fork)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ui-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python deps
        run: pip install pyyaml

      - name: Generate Kotlin test from YAML
        run: |
          python3 tools/yaml_to_kotlin.py \
            --input test_flow.yml \
            --output app/src/androidTest/java/com/example/myapp/GeneratedUiTest.kt

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Start Emulator & Run Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel
          script: ./gradlew connectedAndroidTest

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: '**/screenshots/*.png'
          retention-days: 7

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: '**/build/reports/androidTests/*'
          retention-days: 7
